name = "Card Flow"
license = "MIT"
licenselink =
    "//github.com/digitalcraftsman/hugo-icarus-theme/blob/master/LICENSE.md"
description = "The blog theme you may fall in love with, coming to Hugo."
homepage = "//github.com/digitalcraftsman/hugo-icarus-theme"
tags = ["syntax highlighting", "maxthjax", "rss",
    "gallery", "widgets", "google analytics"]
features = ["syntax highlighting", "maxthjax", "rss",
    "gallery", "widgets", "google analytics"]
min_version = 0.20

[author]
  name = "Eric Gregorich"
  homepage = "//ericgregorich.com"

# If porting an existing theme
[original]
  name = "Micro.blog Default Theme"
  homepage = "github.com/microdotblog/theme-default.git"
repo = "//github.com/microdotblog/theme-default.git"
